### ISSUE TITLE
Please resubmit Dual Compute Unit to Tiny Tapeout 05

### ISSUE THREAD

**Issue by urish** [himanshu5-prog/tt_um_myChip#1]
Hi Himanshu,

We have done some internal changes to Tiny Tapeout 05 that require resubmission of the project to the shuttle. It takes only two steps:

1. Rerun the [GDS workflow](https://github.com/himanshu5-prog/tt_um_myChip/actions/workflows/gds.yaml) in this repo and wait for it to complete (or, if you create a new commit, that'll also start the GDS workflow)
2. Go to https://app.tinytapeout.com/ (sign in as needed), then choose your project from the list and click the blue "SUBMIT A NEW REVISION" button

Thanks!

**Comment by himanshu5-prog** [comment]
Thanks Urish.
I have re-run the gds flow and submitted through the link. Thanks again for letting me know about the changes.
